### ISSUE TITLE
transfer ownership to OCA

### ISSUE THREAD

**Issue by gurneyalex** [OCA/odoo-sphinx-autodoc#1]
Hello @sylvain-garancher 

As discussed during the code sprint, we would like to setup this project under the OCA umbrella if this is OK with you.

**Comment by Garamotte** [comment]
Hi,

I just transferred the ownership of the package on Pypi to the OCA user.

**Comment by guewen** [comment]
I guess we can close this issue. Thanks @sylvain-garancher :-)
